// 4.Vue2Host/host/src/App.vue
<template>
  <div>
    <div id="navbar"></div>
</div>
</template>
<script>
  import mountFooter from 'vue3App/mountFooter';
  import mountFeature from 'host/mountFeature'  
  import navbarWrapper from 'reactApp/navbarWrapper'
  
  export default {
  components: {
}, mounted(){
  navbarWrapper('navbar');
  mountFooter('#footer');
}

}
</script>

// 4.Vue2Host/reactApp/src/App.jsx
import React from "react";
import ReactDOM from "react-dom";
import Navbar from "./Navbar"
import "./index.scss";
import mountFooter from "vue3App/mountFooter";
import mountFeature from "host/mountFeature";



const App = () => {
  mountFooter('#footer')
  return (
  <>
    <Navbar/>
  </>
  )
};
ReactDOM.render(<App />, document.getElementById("app"));
