// 4.Vue2Host/reactApp/src/App.jsx
import React from "react";
import ReactDOM from "react-dom";
import Navbar from "./Navbar"
import "./index.scss";
import mountFooter from "vue3App/mountFooter";
import mountFeature from "host/mountFeature";



const App = () => {
  mountFooter('#footer')
  return (
  <>
    <Navbar/>   
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: reactApp</div>
    <div>Framework: react</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
  </>
  )
};
ReactDOM.render(<App />, document.getElementById("app"));

// 2. VueHostVueClient/host/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: host</div>
    <div>Framework: vue3</div>
    <div>Language: TypeScript</div>
    <div>CSS: Tailwind</div>
    <App/>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'
  import App from "remote1/App";

  export default defineComponent({ components: { App } });
</script>
