// 5.Vue3Host/vue3host/src/App.vue
<template>
    <Header/>
    <Card/>
    <div id="vue2Feature"></div>
    <vue2Feature/>
  <div id="footer"></div>
</template>

<script>
  import Header from 'vue3host/Header'
  import Feature from "vue2App/Feature"
  import { vue2ToVue3 } from './utils';
  import Footer from 'reactApp/Footer';
  import Card from 'vue3App/Card'
  import mountFooter from 'reactApp/mountFooter'

  export default {
    components: {
      Header,
      Card,
      vue2Feature: vue2ToVue3(Feature, 'vue2Feature'),
      Footer
    }, mounted(){
      mountFooter('footer');
    }
  }

</script>

// 5.Vue3Host/reactApp/src/App.jsx
import React from "react";
import ReactDOM from "react-dom";
import Footer from "reactApp/Footer"
import "./index.scss";
import Header from 'vue3host/Header'
import Feature from "vue2App/Feature"
import Card from 'vue3App/Card'



const App = () => (
  <>
  <div id="header"></div>
  <div id="feature"></div>
  <div id="card"></div>
  <Footer/>
  </>
);
ReactDOM.render(<App />, document.getElementById("app"));
ReactDOM.render(<Header/>, document.getElementById("header"));
ReactDOM.render(<Feature/>, document.getElementById("feature"));
ReactDOM.render(<Card/>, document.getElementById("card"));
